<?php

// $Id$
/**
 * @file
 * This file is created to show custom pager creation in drupal.
 * 
 */

/**
 * Implementation of hook_menu()
 */
function custom_cache_check_menu() {
    $items = array();
    $items['custom-cache-check'] = array(
        'title' => t('Custom Cache Check'),
        'page callback' => 'custom_cache_check',
        'access arguments' => array('administer site configuration'),
        'type' => MENU_NORMAL_ITEM,
    );




    return $items;
}

function custom_cache_check() {

    $output = '';
    $output .= drupal_render(drupal_get_form('custom_cache_check_form'));
    if (isset($_GET['cid'])) {
        $output .= custom_cache_data($_GET['cid']);
    }
    return $output;
}

function custom_cache_check_form() {
    if (isset($_GET['cid'])) {
        $default_value = $_GET['cid'];
    } else {
        $default_value = '';
    }
    $form['name'] = array(
        '#type' => 'textfield',
        '#title' => 'Name of Cache',
        '#required' => TRUE,
        '#size' => 60,
        '#default_value' => $default_value,
        '#maxlength' => 120,
    );


    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Submit')
    );

    return $form;
}

function custom_cache_check_form_submit($form, &$form_state) {
    $name = $form_state['values']['name'];
    $q = array('query' => array('cid' => $name));
    drupal_goto('custom-cache-check', $q);
}

function custom_cache_data($name) {

    $output = '';
    $header = array('cid', 'Now', 'Created', 'Expire');

    $sql = "SELECT cid, DATE_FORMAT(now(), '%d-%m-%Y : %H %i %s') AS current, DATE_FORMAT(FROM_UNIXTIME(created), '%d-%m-%Y : %H %i %s') AS created, DATE_FORMAT(FROM_UNIXTIME(expire), '%d-%m-%Y : %H %i %s') AS expired FROM {cache} WHERE cid LIKE '%$name%'";

    $result = db_query($sql);


    $data = array();

    foreach ($result as $rows) {

        $data[] = array($rows->cid, $rows->current, $rows->created, $rows->expired);
    }
    $output .= theme('table', array('header' => $header, 'rows' => $data, 'caption' => '', 'sticky' => TRUE, 'empty' => 'No data found...', 'id' => 'my-custom-id', 'class' => 'my-custom-class', 'border' => 3));

    $output .= theme('pager');
    return $output;
    return $name;
}

