<?php

function custom_form_menu() {
    $items = array();
    $items['custom-form'] = array(
        'title' => t('Custom Form Element'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('custom_form'),
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'file' => 'inc/custom_form.inc',
    );
    $items['custom-form/first'] = array(
        'title' => t('Form Demo '),
        //'page callback' => 'first_menu_default_tab',
        'access arguments' => array('access content'),
        'type' => MENU_DEFAULT_LOCAL_TASK,
        'weight' => 1,
    );
    $items['custom-form/first/tab'] = array(
        'title' => t('Simple Form'),
        //'page callback' => 'first_menu_default_tab',
        'access arguments' => array('access content'),
        'type' => MENU_DEFAULT_LOCAL_TASK,
        'weight' => 1,
    );
    $items['custom-form/first/tab1'] = array(
        'title' => t('Form Elements Demo'),
        'page callback' => 'first_menu_tab_first_tab2',
        'access arguments' => array('access content'),
        'type' => MENU_LOCAL_TASK,
        'weight' => 2,
        'file' => 'inc/first_menu_tab_first_tab2.inc',
    );
    $items['custom-form/first/tab2'] = array(
        'title' => t('Adding checkboxes to a table'),
        'page callback' => 'first_menu_tab_second_tab2',
        'access arguments' => array('access content'),
        'type' => MENU_LOCAL_TASK,
        'weight' => 3,
        'file' => 'inc/first_menu_tab_second_tab2.inc'
    );
    $items['custom-form/first/tab3'] = array(
        'title' => t('Multistep Form'),
        'page callback' => 'custom_multistep_form',
        'access arguments' => array('access content'),
        'type' => MENU_LOCAL_TASK,
        'weight' => 3,
        'file' => 'inc/custom_multistep_form.inc'
    );

    $items['custom-form/second'] = array(
        'title' => t('Ajax form'),
        'page callback' => 'custom_auto_form',
        'access arguments' => array('access content'),
        'type' => MENU_LOCAL_TASK,
        'weight' => 2,
        'file' => 'inc/custom_auto_form.inc',
    );
    $items['custom-form/second/autocomplete'] = array(
        'title' => t(''),
        'page callback' => 'custom_auto_data',
        'access arguments' => array('access content'),
        'type' => MENU_LOCAL_TASK,
        'weight' => 1,
        'file' => 'inc/custom_auto_form.inc',
    );
    $items['custom-form/second/tab'] = array(
        'title' => t('Auto complete'),
        //'page callback' => 'second_menu_tab_default_tab',
        'access arguments' => array('access content'),
        'type' => MENU_DEFAULT_LOCAL_TASK,
    );

    $items['custom-form/second/tab/autocomplete'] = array(
        'title' => t(''),
        'page callback' => 'second_menu_tab_default_tab_autocomplete',
        'access arguments' => array('access content'),
        'file' => 'inc/second_menu_tab_default_tab2.inc',
        'weight' => 1,
    );



    $items['custom-form/second/tab0'] = array(
        'title' => t('Comma Seperated Auto-complete'),
        'page callback' => 'second_menu_tab_default_tab2',
        'access arguments' => array('access content'),
        'type' => MENU_LOCAL_TASK,
        'weight' => 2,
        'file' => 'inc/second_menu_tab_default_tab2.inc',
    );

    $items['custom-form/second/tab1'] = array(
        'title' => t('Auto Complete with hidden field'),
        'page callback' => 'second_menu_tab_second_tab21',
        'access arguments' => array('access content'),
        'type' => MENU_LOCAL_TASK,
        'file' => 'inc/second_menu_tab_second_tab21.inc',
        'weight' => 3,
    );
    $items['custom-form/second/tab2'] = array(
        'title' => t('Dynamic Form Elements'),
        'page callback' => 'second_menu_tab_second_tab22',
        'access arguments' => array('access content'),
        'type' => MENU_LOCAL_TASK,
        'file' => 'inc/second_menu_tab_second_tab22.inc',
        'weight' => 4,
    );
    return $items;
}

/**
 * Implementation of hook_theme()

 * */
function custom_form_theme() {

    $path = drupal_get_path('module', 'custom_form');

    $template = array();
    $template['custom_form'] = array('template' => 'custom-form', 'render element' => 'form', 'path' => $path . '/templates');

    return $template;
}

