<?php

// $Id$
/**
 * @file
 * This file is created to show drupal menu system.
 */
/**
 * Implementation of hook_perm()
 *
 */
/* function menu_tab_perm()
  {
  return array('mera form');
  } */

/**
 * Implementation of hook_menu()
 */
/*
  #####################################################################################################
  'access arguments' has four values:=>
  1>.'access arguments' => TRUE --> means this menu item is visible to any type of user

  2>. 'access arguments' => array('access content') --> only visible to that user type
  having permission to access content  of 'node module' (admin/user/permissions page)

  3>.'access arguments' => array('admin site configuraion') --> only admin can see this page

  4>. 'access arguments' => array('value define in hook_perm') --> only visible to that user type
  have permission to view that page

  menu 'type' has also four value:=>

  1>. 'type' =>MENU_NORMAL_ITEM --> creates a menu item in drupal admin navigation
  2>. 'type' => MENU_CALLBACK --> Only menu path is created.
  3>. 'type' => MENU_DEFAULT_LOCAL_TASK --> creates default tab on a page
  4>. 'type' => MENU_LOCAL_TASK  --> creates tabs except default tab

  Note:=> 1>. When you create a defautl tab there is not need to define 'page callback' because
  it renders it parent menu 'page callback'. parent menu must not be a 'type' => MENU_DEFAULT_LOCAL_TASK,
  it is either a 'type' =>MENU_NORMAL_ITEM or a 'type' => MENU_CALLBACK type.

  2>. url of 'type' => MENU_DEFAULT_LOCAL_TASK, is same has it's parent. only url is define to
  follow drupal articuture.




  #####################################################################################################
 */

function menu_tab_menu() {
    $items = array();
    $items['custom-menu'] = array('title' => t('Demo of custom menu'),
        'page callback' => 'first_menu_default_tab',
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
    );
    $items['custom-menu/first'] = array('title' => t('First custom menu '),
        //'page callback' => 'first_menu_default_tab',
        'access arguments' => array('access content'),
        'type' => MENU_DEFAULT_LOCAL_TASK,
    );
    $items['custom-menu/first/tab'] = array('title' => t('First custom menu default tab'),
        //'page callback' => 'first_menu_default_tab',
        'access arguments' => array('access content'),
        'type' => MENU_DEFAULT_LOCAL_TASK,
    );
    $items['custom-menu/first/tab1'] = array('title' => t('First custom menu second tab'),
        'page callback' => 'first_menu_tab_first_tab',
        'access arguments' => array('access content'),
        'type' => MENU_LOCAL_TASK,
    );
    $items['custom-menu/first/tab2'] = array('title' => t('First custom menu third tab'),
        'page callback' => 'first_menu_tab_second_tab',
        'access arguments' => array('access content'),
        'type' => MENU_LOCAL_TASK,
    );

    $items['custom-menu/second'] = array('title' => t('Second custom menu'),
        'page callback' => 'second_menu_tab_default_tab',
        'access arguments' => array('access content'),
        'type' => MENU_LOCAL_TASK,
        ''
    );
    $items['custom-menu/second/tab'] = array('title' => t('Second custom menu default tab'),
        //'page callback' => 'second_menu_tab_default_tab',
        'access arguments' => array('access content'),
        'type' => MENU_DEFAULT_LOCAL_TASK,
        ''
    );
    $items['custom-menu/second/tab1'] = array('title' => t('Second custom menu second tab'),
        'page callback' => 'second_menu_tab_second_tab',
        'access arguments' => array('access content'),
        'type' => MENU_LOCAL_TASK,
        ''
    );
    return $items;
}

function first_menu_default_tab() {
    $output = t('This is first menu default tab content');
    return $output;
}

/* function second_menu_tab()
  {
  $output = t('This is second form section');
  return $output;
  } */

function first_menu_tab_first_tab() {
    $output = t('This is first menu first tab content');
    return $output;
}

function first_menu_tab_second_tab() {
    $output = t('This is first menu second tab content');
    return $output;
}

function second_menu_tab_default_tab() {
    $output = t('This is second menu default tab content');
    return $output;
}

/* function third_menu_tab_first_tab()
  {
  $output = t('This is second form section first tab');
  return $output;
  } */

function second_menu_tab_second_tab() {
    $output = t('This is second menu second tab content');
    return $output;
}

