<?php

// $Id$
/**
 * @file
 * This file is created to show custom pager creation in drupal.
 * 
 */

/**
 * Implementation of hook_node_insert()
 *
 */
function custom_node_event_node_insert($node) {
    global $language;

    if ($node->type == 'article') {
        $nid = $node->nid;
        $type = $node->type;
        $title = $node->title;
        $path = 'node/' . $nid;
        $nodePath = url($path, $options = array('absolute' => TRUE));
        $message = $nid . "---" . $type . "---" . $title . "---" . $nodePath;
        $resCode = drupal_http_request($nodePath);

        drupal_set_message($resCode->code . "<b>Insert: </b> " . $message);
    }
}

/**
 * Implementation of hook_node_update()
 *
 */
function custom_node_event_node_update($node) {
    global $language;
    if ($node->type == 'article') {

        $nid = $node->nid;
        $type = $node->type;
        $title = $node->title;
        $path = 'node/' . $nid;
        $nodePath = url($path, $options = array('absolute' => TRUE));
        $message = $nid . "---" . $type . "---" . $title . "---" . $nodePath;
        $resCode = drupal_http_request($nodePath);
        drupal_set_message($resCode->code . " <b>Update: </b> " . $message);
    }
}

/**
 * Implementation of hook_node_delete()()
 *
 */
function custom_node_event_node_delete($node) {
    global $language;
    if ($node->type == 'article') {

        $nid = $node->nid;
        $type = $node->type;
        $title = $node->title;
        $path = 'node/' . $nid;
        $nodePath = url($path, $options = array('absolute' => TRUE));
        $message = $nid . "---" . $type . "---" . $title . "---" . $nodePath;
        $resCode = drupal_http_request($nodePath);
        drupal_set_message($resCode->code . "<b>Delete: </b> " . $message);
    }
}

