<?php
// $Id$
/**
*@file
* This file is created to show custom pager creation in drupal.
* 
*/



/**
* Implementation of hook_menu()
*/



function custom_user_create_menu()
{
	$items = array();
	$items['custom-user-create'] = array(
                          'title' => t('Custom User Create'),
		                  'page callback' => 'mycustom_user_create',
				          'access arguments' => array('access content'),
                                  'file' => 'inc/custom_user_create.inc',
				          'type' =>MENU_NORMAL_ITEM,
		                  );
        $items['custom-user-update'] = array(
                          'title' => t('Custom User Update'),
                                  'page callback' => 'mycustom_user_update',
                                          'access arguments' => array('access content'),
                                  'file' => 'inc/custom_user_update.inc',
                                          'type' =>MENU_NORMAL_ITEM,
                                  );


	
	
	
	return $items;
}



