<?php
// $Id$
/**
*@file
* This file is created to show custom pager creation in drupal.
* 
*/





/**
* Implementation of hook_perm()
*
*/

function testing_perm()
{
	return array('test page test' => array('title'=> t('test page permission txt'), 'description'=> t('This is description')));
}
/**
* Implementation of hook_menu()
*/



function testing_menu()
{
	$items = array();
	$items['testing'] = array(
                          'title' => t('Testing'),
		                  'page callback' => 'group_sponsor_ad_show',
				          'access arguments' => array('test page test'),
				          'type' =>MENU_NORMAL_ITEM,
		                  );
$items['%/archive/%'] = array(
                          'title' => t('Archive'),
		                  'page callback' => 'archieve_data',
                                  'page arguments' => array(0,1),
				  'access arguments' => TRUE,
				   'type' =>MENU_NORMAL_ITEM,
		                  );
	
	
	
	return $items;
}


function group_sponsor_ad_show()
{
 
 $output = '';
 $tid_arr = array(8, 10, 11, 12);
 $tid_arr_replace = array(13, 14);
    $sql = "SELECT DISTINCT entity_id AS nid FROM field_data_field_muti_category WHERE field_muti_category_tid IN (8, 10, 11, 12) AND entity_type = 'node' AND bundle ='page';";

 $result = db_query($sql);   
 foreach($result as $row){
		
		
                $nd = node_load($row->nid);
                $field = $nd ->field_muti_category;
                $langArr = array_keys($field);
                $fieldLang = $langArr[0];
                $fieldLangValues = $field[$fieldLang];
                foreach($fieldLangValues AS $key => $value){
                    
                        if (in_array(11, $value))
                      {
                             $arrCount = count($fieldLangValues);
                             
                             foreach($tid_arr_replace AS $value){
                                  $nd ->field_muti_category[$fieldLang][$arrCount]['tid'] = $value; 
                                  $arrCount++;
                                 
                             }
                            
                             
                             node_save($nd);
                         $output .= $row->nid ."---";
                      }
                }
	}
	
	
	return $output;

 

}


function archieve_data($first = ''){

    return 'hi '.$first;
}
