<?php

// $Id$
/**
 * @file
 * This file is created to show custom pager creation in drupal.
 * 
 */

/**
 * Implementation of hook_form_alter()

 */
function custom_form_theme_form_alter(&$form, &$form_state, $form_id) {

    if ($form_id == 'user_register_form') {

        $form['#theme'] = 'user_register';
    }

    if ($form_id == 'user_login_block') {

        // print_r($form);

        $form['name']['#title'] = t('Naam');
        $form['name']['#default_value'] = t('Enter your name');
        $form['pass']['#title'] = t('Pass');
        $form['pass']['#default_value'] = 'Enter your name';
        $form['actions']['submit']['#value'] = t('Press for login');
        $form['#theme'] = 'custom_user_login_bar';
    }
}

/**
 * Implementation of hook_theme()
 */
//  HOW TO THEME NODE FORM
function custom_form_theme_theme() {


    $path = drupal_get_path('module', 'custom_form_theme');
    $template = array();
    $template['article_node_form'] = array('template' => 'article-node-form', 'render element' => 'form', 'path' => $path . '/templates');

    return $template;
}
